- name: Make sure packages are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - epel-release
  - python-setuptools
  - python2-pip

- name: install dependices
  pip:
    name: "{{ item }}"
    state: present
  with_items:
  - docker
